name: CI/CD with Docker + Vercel

on:
  push:
    branches:
      - main

jobs:
  # --- CI: Build bằng Docker ---
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image (CI test only)
        run: docker build -t task-app:ci .

  # --- CD: Deploy lên Vercel ---
  deploy:
    runs-on: ubuntu-latest
    needs: build   # chỉ chạy khi job build thành công

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment Info
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build project with Vercel
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
